CREATE DATABASE ADO_SQL
USE ADO_SQL

CREATE TABLE TBL_ADO
(
AID INT PRIMARY KEY IDENTITY,
NAME VARCHAR(50),
AGE INT,
PHONE BIGINT,
COUNTRY INT,
STATE INT
)
SELECT * FROM TBL_ADO

CREATE PROCEDURE PROC_ADO
@ACTION VARCHAR(50)=NULL,
@AID INT=0,
@NAME VARCHAR(50)=NULL,
@AGE INT=0,
@PHONE BIGINT=0,
@COUNTRY INT=0,
@STATE INT=0
AS
BEGIN
IF(@ACTION = 'INS')
BEGIN
INSERT INTO TBL_ADO(NAME,AGE,PHONE,COUNTRY,STATE)VALUES(@NAME,@AGE,@PHONE,@COUNTRY,@STATE)
END
ELSE IF(@ACTION = 'DIS')
BEGIN
SELECT * FROM TBL_ADO JOIN TBL_COUNTRY ON COUNTRY = CID JOIN TBL_STATE ON STATE = SID
END
ELSE IF(@ACTION = 'DEL')
BEGIN
DELETE FROM TBL_ADO WHERE AID = @AID
END
ELSE IF(@ACTION = 'EDT')
BEGIN
SELECT * FROM TBL_ADO WHERE AID = @AID
END
ELSE IF(@ACTION = 'UPD')
BEGIN
UPDATE TBL_ADO SET NAME=@NAME, AGE=@AGE, PHONE=@PHONE, COUNTRY=@COUNTRY, STATE=@STATE WHERE AID=@AID
END
END
SP_HELPTEXT 'PROC_ADO'



CREATE TABLE TBL_COUNTRY
(
CID INT PRIMARY KEY IDENTITY,
CNAME VARCHAR(50)
)
SELECT * FROM TBL_COUNTRY
INSERT INTO TBL_COUNTRY(CNAME)VALUES('INDIA')
INSERT INTO TBL_COUNTRY(CNAME)VALUES('PAKISTAN')
INSERT INTO TBL_COUNTRY(CNAME)VALUES('BHUTAN')

CREATE TABLE TBL_STATE
(
SID INT PRIMARY KEY IDENTITY,
CID INT,
SNAME VARCHAR(50)
)
SELECT * FROM TBL_STATE
INSERT INTO TBL_STATE(CID,SNAME)VALUES('1','BIHAR')
INSERT INTO TBL_STATE(CID,SNAME)VALUES('1','UTTAR PRADESH')
INSERT INTO TBL_STATE(CID,SNAME)VALUES('1','NAGALAND')

INSERT INTO TBL_STATE(CID,SNAME)VALUES('2','KHYBER')
INSERT INTO TBL_STATE(CID,SNAME)VALUES('2','SINDH')
INSERT INTO TBL_STATE(CID,SNAME)VALUES('2','ISLAMABAD')

INSERT INTO TBL_STATE(CID,SNAME)VALUES('3','HAA')
INSERT INTO TBL_STATE(CID,SNAME)VALUES('3','DAGA')
INSERT INTO TBL_STATE(CID,SNAME)VALUES('3','PARO')